### ISSUE TITLE
I get unknown error issue about Thread

### ISSUE THREAD

**Issue by yangjunsss** [ericwlange/AndroidJSCore#4] opened 2015-12-21 10:41 UTC
When I try to use new JSContext object, I get the Unknown Error Exception message, and I fix it by put all code into other thread to run, Have you get any kind of this issue? 

My env is Android 4.3 on SAMSUNG SCH-N719

**Comment by ericwlange** [comment] 2015-12-23 16:11
I am having trouble parsing what exact error you are receiving.  Can you provide some code snippets and/or the dalvik log?

**Comment by yangjunsss** [comment] 2016-01-01 06:23
```
01-01 14:19:19.336 24980-24980/cn.qingcloud.qcconsole W/System.err: Unknown Error
01-01 14:19:19.336 24980-24980/cn.qingcloud.qcconsole W/System.err:     at org.liquidplayer.webkit.javascriptcore.JSContext.evaluateScript(JSContext.java:129)
01-01 14:19:19.336 24980-24980/cn.qingcloud.qcconsole W/System.err:     at org.liquidplayer.webkit.javascriptcore.JSContext.evaluateScript(JSContext.java:151)
...
01-01 14:19:19.341 24980-24980/cn.qingcloud.qcconsole W/System.err:     at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1024)
01-01 14:19:19.341 24980-24980/cn.qingcloud.qcconsole W/System.err:     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4702)
01-01 14:19:19.346 24980-24980/cn.qingcloud.qcconsole W/System.err:     at android.app.ActivityThread.access$1400(ActivityThread.java:168)
01-01 14:19:19.346 24980-24980/cn.qingcloud.qcconsole W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1389)
01-01 14:19:19.346 24980-24980/cn.qingcloud.qcconsole W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:99)
01-01 14:19:19.346 24980-24980/cn.qingcloud.qcconsole W/System.err:     at android.os.Looper.loop(Looper.java:137)
01-01 14:19:19.346 24980-24980/cn.qingcloud.qcconsole W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5493)
01-01 14:19:19.346 24980-24980/cn.qingcloud.qcconsole W/System.err:     at java.lang.reflect.Method.invokeNative(Native Method)
01-01 14:19:19.346 24980-24980/cn.qingcloud.qcconsole W/System.err:     at java.lang.reflect.Method.invoke(Method.java:525)
01-01 14:19:19.346 24980-24980/cn.qingcloud.qcconsole W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1209)
01-01 14:19:19.346 24980-24980/cn.qingcloud.qcconsole W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1025)
01-01 14:19:19.346 24980-24980/cn.qingcloud.qcconsole W/System.err:     at dalvik.system.NativeStart.main(Native Method)
```


```
  public void executeJsFile(final String fileName){
       // threadPool.execute(new Runnable() {
        //    @Override
         //   public void run() {
                try{
                    context = new JSContext();
                    InputStream is = InitApplication.getInstance().getAssets().open(fileName);
                    BufferedReader r = new BufferedReader(new InputStreamReader(is));
                    StringBuffer sb = new StringBuffer();
                    String line;
                    while ((line = r.readLine()) != null){
                        sb.append(line);
                    }
                    is.close();
                    context.evaluateScript(sb.toString().trim());
                } catch (JSException e) {
                    e.printStackTrace();
                } catch (IOException e) {
                    e.printStackTrace();
                }
        //    }
       // });
    }
```

**Comment by ericwlange** [comment] 2016-01-01 16:26
It appears as if the JS code itself is throwing an exception.  Can you post the JS?

**Comment by ericwlange** [comment] 2016-01-23 06:29
I have now run into this problem.  I didn't see it until I built for API < 19.  The issue is that the main thread's stack size appears to only be about 16K, where a standard pthread has a 1MB stack.  This is more pronounced on older builds of Android.  I am fixing this now.

**Comment by ericwlange** [comment] 2016-01-27 03:17
This is fixed in head.  It will go into the 2.1 release as soon as I package it up.  All operations now run in a separate dispatch queue, which is a special thread.  It solves this problem, plus has the added benefit of ensuring thread safety.

**Comment by ericwlange** [comment] 2016-01-27 17:54
This is now fixed in 2.1.  Closing this issue.  Cheers.

**Comment by yangjunsss** [comment] 2016-01-29 16:40
Cool!

**Comment by yangjunsss** [comment] 2016-02-19 10:09
I updated from 1.0 to 2.1 using the source code, not the aar because I would like to use Android Studio productFlavors to decrease the apk size. 
Unfortunately, the context.evaluateScript func is blocking in current thread, I can't get the func return.
But the 1.0 can work for me.

**Comment by ericwlange** [comment] 2016-02-28 04:05
Do you have a simple test case that fails?

**Comment by ericwlange** [comment] 2016-02-28 04:06
Also have you tried with the aar to see if that works first?  It would be helpful to know where the breakdown is.

**Comment by tehcpu** [comment] 2016-02-28 04:22
Unfortunately, I have the same problem, and I use the aar from 2.1 release. Currently, I can't to detect whats wrong with it, cause my js-file is 4 KB in min-mode D: (So, I will have a lot of pain with breakpointing) Now, I temporarily downgrade it to 2.0, and it works fine again.
So, @yangjunsss's trouble is real, and seems like reason isn't in compilation type :(

**Comment by ericwlange** [comment] 2016-02-28 06:52
That's helpful. The major difference between 2.0 and 2.1 is the threading
support so it sounds like something is broken there. I am guessing I missed
a deadlock condition somewhere.  I will take a look at it. Please send me
any simple cases that you come across.

**Comment by ericwlange** [comment] 2016-05-01 03:54
I have created a [2.2 pre-release](https://github.com/ericwlange/AndroidJSCore/releases/tag/2.2-pre1).  Let me know if that has any impact on the problem.  A number of stability fixes have gone in.

**Comment by ericwlange** [comment] 2016-05-22 11:15
This bug is now fixed.  Please try the latest pre-release (2.2-pre2) and verify that it works.

**Comment by ericwlange** [comment] 2016-05-31 11:41
Marking as duplicate of [#24](https://github.com/ericwlange/AndroidJSCore/issues/24).  Should be fixed.

**Closed by ericwlange** 2016-05-31 11:41 UTC
